### ISSUE TITLE
I can't open my dashboard

### ISSUE THREAD

**Issue by naivescrooge** [ZsgsDesign/NOJ#638]
My dashboard can't be open and there is another me in a group

**Comment by ZsgsDesign** [comment]
Is the second the same with #629?

You need to provide more information, like error logs and screenshots or so on or we cannot figure out the problem.

If you are using `APP_DEBUG=true` remember to censor sensitive informations and then upload, or you can paste logs manually.

**Comment by naivescrooge** [comment]
![image](https://user-images.githubusercontent.com/58645280/130513532-4fd40800-342b-49bb-ac4b-9687c1889128.png)
That is the screenshot. Btw, the setting page has the same error.
The error logs are "GET https://acm.njupt.edu.cn/account/settings 500" and "GET https://acm.njupt.edu.cn/account/dashboard 500"

**Comment by ZsgsDesign** [comment]
I would not be able to check the detailed error log till outbould network reopens, it might happen this afternoon when they reassessed system security risks. If it's a bug a patch will be pushed today.

**Comment by ZsgsDesign** [comment]
You can IM me via QQ, it comes the same as my email address.

**Comment by ZsgsDesign** [comment]
Oh, I see, it's the bug causing by recent outbound network restrictions by *relevant gov department*, see #634.

A compatibility patch would be available right now but also, due to recent outbound network restrictions, NJUPT Online Judge would not receiving this patch until they reassessed system security risks.
